name: Install Dependencies

on:
  push:
    branches:
      - main  # Déclenche le workflow sur des push vers la branche principale

jobs:
  install:
    runs-on: ubuntu-latest  # Utilisation d'un environnement Ubuntu

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt